server {
    listen 80;
    server_name localhost;
    access_log /var/log/nginx/access.log debug_proxy;
    root /app/src;

    location = /handlebars/dist/handlebars.runtime.js {
        root /app/node_modules;
        try_files /handlebars/dist/handlebars.runtime.js =404;
    }

    location = / {
        return 302 /app/index.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}



